spring:
  datasource:
    url: jdbc:mysql://localhost:3306/entry
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

#  jackson:
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
