version: '3'

services:
  mysql:
    image: mysql:8.0
    networks:
      - msa_network
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  redis-master:
    image: redis:latest
    container_name: redis-master
    networks:
      - msa_network
    ports:
      - "6379:6379"
    volumes:
      - ./redis/master/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis-replica:
    image: redis:latest
    container_name: redis-replica
    networks:
       - msa_network
    depends_on:
      - redis-master
    ports:
      - "6380:6379"
    volumes:
      - ./redis/replica/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis-sentinel:
    image: redis:latest
    container_name: redis-sentinel
    networks:
      - msa_network
    depends_on:
      - redis-master
    ports:
      - "26379:26379"
    volumes:
      - ./redis/sentinel/sentinel.conf:/usr/local/etc/redis/sentinel.conf
    command: ["redis-sentinel", "/usr/local/etc/redis/sentinel.conf"]

  eureka-server:
    image: ecommerce-msa-server-eureka-server:0.0.1
    networks:
      - msa_network
    ports:
      - "8761:8761"

  gateway-server:
    image: ecommerce-msa-server-gateway-server:0.0.1
    networks:
      - msa_network
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JWT_SECRET=dudguswntjdtkdwlsdbstjrahenahencnldjqtjdrhd
      - EUREKA_SERVER_HOST=eureka-server

  user-service:
    image: ecommerce-msa-server-user-service:0.0.1
    networks:
      - msa_network
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JWT_SECRET=dudguswntjdtkdwlsdbstjrahenahencnldjqtjdrhd
      - EUREKA_SERVER_HOST=eureka-server

  order-service:
    image: ecommerce-msa-server-order-service:0.0.1
    networks:
      - msa_network
    ports:
      - "8082:8080"
    depends_on:
      - mysql
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - EUREKA_SERVER_HOST=eureka-server
      - PRODUCT_SERVER_HOST=product-service


  payment-service:
    image: ecommerce-msa-server-payment-service:0.0.1
    networks:
      - msa_network
    ports:
      - "8083:8080"
    depends_on:
      - mysql
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - EUREKA_SERVER_HOST=eureka-server

  product-service:
    image: ecommerce-msa-server-product-service:0.0.1
    networks:
      - msa_network
    ports:
      - "8084:8080"
      - "5043:5043"
    depends_on:
      - mysql
      - redis-sentinel
      - eureka-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpw
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - EUREKA_SERVER_HOST=eureka-server
      - REDIS_SENTINEL_HOST=redis-sentinel
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=DEBUG
      - LOGGING_LEVEL_ORG_HIBERNATE_TYPE_DESCRIPTOR_SQL_BASICBINDER=TRACE
networks:
  msa_network:
    driver: bridge