name: NOTIFICATION CI - Test Coverage 검증

on:
  pull_request:
    branches: [ "notification-develop" ]

jobs:
  build:
    permissions:
      pull-requests: write

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./notification-service

    steps:
      - name: Checkout to current repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-write-only: true

      - name: Grant execute permission for gradlew
        run: chmod +x ../gradlew

      - name: Run clean tests and generate coverage report
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
        run: ../gradlew :notification-service:clean test jacocoTestReport
        continue-on-error: true

      - name: Verify test coverage
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
        run: ../gradlew :notification-service:jacocoTestCoverageVerification
        continue-on-error: true

      - name: Report test Coverage to PR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          title: 📌 Test Coverage Report
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.CICD_TOKEN }}
          min-coverage-overall: 70
          min-coverage-changed-files: 70
          update-comment: true